# Generated by Django 3.2.8 on 2021-10-21 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211012_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20211011_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', through='accounts.Contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevée')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, choices=[('A FAIRE', 'A faire'), ('EN-COURS', 'En-cours'), ('TERMINE', 'Terminé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(blank=True, choices=[('BUG', 'Bug'), ('AMELIORATION', 'Amélioration'), ('TACHE', 'Tâche')], max_length=20, null=True),
        ),
    ]
