# Generated by Django 3.2.8 on 2021-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('user_id', 'project_id'), name='unique-contributor'),
        ),
    ]
